version: '3'
services:
  new:
    container_name: NewProject
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      # - "8080:8080"
      # - "443:443"
    volumes:
      # change custom path
      - D:/Works/NewProject:/var/www/approot
    # command: bash /run.sh

#Docker Networks
networks:
  app-network:
    driver: bridge